# Generated by Django 3.1.3 on 2020-11-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicago', '0009_query10_query11'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_RequestsGeneralInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=120)),
                ('creation_date', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=120)),
                ('completion_date', models.CharField(max_length=120)),
                ('service_request_number', models.CharField(max_length=120)),
                ('type_of_service_request', models.CharField(max_length=120)),
            ],
        ),
    ]
