# Generated by Django 3.1.3 on 2020-11-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicago', '0010_add_requestsgeneralinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_requestsgeneralinfo',
            name='completion_date',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='add_requestsgeneralinfo',
            name='creation_date',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='add_requestsgeneralinfo',
            name='service_request_number',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='add_requestsgeneralinfo',
            name='status',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
