# Generated by Django 3.1.3 on 2020-11-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicago', '0013_auto_20201119_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_RequestsGeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(blank=True, default='', max_length=120)),
                ('zip_code', models.CharField(blank=True, default='', max_length=120)),
                ('wards', models.CharField(blank=True, default='', max_length=120)),
                ('police_district', models.CharField(blank=True, default='', max_length=120)),
                ('community_area', models.CharField(blank=True, default='', max_length=120)),
                ('latitude', models.CharField(blank=True, default='', max_length=120)),
                ('longitude', models.CharField(blank=True, default='', max_length=120)),
                ('historical_wards', models.CharField(blank=True, default='', max_length=120)),
                ('zip_codes', models.CharField(blank=True, default='', max_length=120)),
                ('community_areas', models.CharField(blank=True, default='', max_length=120)),
                ('census_tracts', models.CharField(blank=True, default='', max_length=120)),
                ('ward', models.CharField(blank=True, default='', max_length=120)),
                ('ssa', models.CharField(blank=True, default='', max_length=120)),
                ('y_coordinate', models.CharField(blank=True, default='', max_length=120)),
                ('x_coordinate', models.CharField(blank=True, default='', max_length=120)),
                ('req_location', models.CharField(blank=True, default='', max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='add_requestsgeneralinfo',
            name='request_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='add_requestsgeneralinfo',
            name='type_of_service_request',
            field=models.CharField(choices=[('Abandoned Vehicle Complaint', 'Abandoned Vehicle Complaint'), ('Garbage Cart Black Maintenance/Replacement', 'Garbage Cart Black Maintenance/Replacement'), ('Graffiti Removal', 'Graffiti Removal'), ('Pot Hole in Street', 'Pot Hole in Street'), ('Rodent Baiting/Rat Complaint', 'Rodent Baiting/Rat Complaint'), ('Sanitation Code Violation', 'Sanitation Code Violation'), ('Street Light Out', 'Street Light Out'), ('Street Lights - All/Out', 'Street Lights - All/Out'), ('Tree Debris', 'Tree Debris'), ('Tree Trim', 'Tree Trim'), ('Vacant/Abandoned Building', 'Vacant/Abandoned Building')], max_length=120),
        ),
    ]
