# Generated by Django 3.1.3 on 2020-11-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicago', '0014_auto_20201119_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_AbandodedBuildings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_of_building', models.CharField(blank=True, max_length=400, null=True)),
                ('building_hazardous', models.CharField(blank=True, max_length=400, null=True)),
                ('building_open', models.CharField(blank=True, max_length=400, null=True)),
                ('entry_point', models.CharField(blank=True, max_length=400, null=True)),
                ('vacant_occupied', models.CharField(blank=True, max_length=400, null=True)),
                ('vacant_due_to_fire', models.CharField(blank=True, max_length=400, null=True)),
                ('people_using_property', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
