# Generated by Django 3.1.3 on 2020-11-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicago', '0015_add_abandodedbuildings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_AbandonedVehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(blank=True, max_length=500, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=160, null=True)),
                ('vehicle_color', models.CharField(blank=True, max_length=60, null=True)),
                ('current_activity', models.CharField(blank=True, max_length=500, null=True)),
                ('most_recent_action', models.CharField(blank=True, max_length=500, null=True)),
                ('days_reported_parked', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
