# Generated by Django 3.1.3 on 2020-11-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicago', '0016_add_abandonedvehicles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_abandonedvehicles',
            name='current_activity',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='add_abandonedvehicles',
            name='days_reported_parked',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='add_abandonedvehicles',
            name='license_plate',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='add_abandonedvehicles',
            name='most_recent_action',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='add_abandonedvehicles',
            name='vehicle_color',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='add_abandonedvehicles',
            name='vehicle_model',
            field=models.CharField(blank=True, default='', max_length=160, null=True),
        ),
    ]
