# Generated by Django 3.1.3 on 2020-11-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicago', '0017_auto_20201119_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_GarbageCarts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_black_carts_delivered', models.CharField(blank=True, default='', max_length=30)),
                ('current_activity', models.CharField(blank=True, default='', max_length=200)),
                ('recent_action', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='add_abandonedvehicles',
            name='current_activity',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='add_abandonedvehicles',
            name='days_reported_parked',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='add_abandonedvehicles',
            name='license_plate',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='add_abandonedvehicles',
            name='most_recent_action',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='add_abandonedvehicles',
            name='vehicle_color',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='add_abandonedvehicles',
            name='vehicle_model',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
