# Generated by Django 3.1.3 on 2020-11-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicago', '0018_auto_20201119_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_GraffitiRemoval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_surface', models.CharField(blank=True, default='', max_length=30)),
                ('where_is_located', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Add_PotHoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_activity', models.CharField(blank=True, default='', max_length=30)),
                ('recent_action', models.CharField(blank=True, default='', max_length=30)),
                ('number_of_potholes_filled_on_block', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
    ]
