# Generated by Django 3.1.3 on 2020-11-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicago', '0019_add_graffitiremoval_add_potholes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_RodentBaiting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_premises_baited', models.CharField(blank=True, default='', max_length=200)),
                ('number_of_premises_with_garbage', models.CharField(blank=True, default='', max_length=200)),
                ('number_of_premises_with_rats', models.CharField(blank=True, default='', max_length=200)),
                ('current_activity', models.CharField(blank=True, default='', max_length=200)),
                ('recent_action', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Add_SanitationCodeComplaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature_of_code_violation', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='add_graffitiremoval',
            name='type_of_surface',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='add_graffitiremoval',
            name='where_is_located',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='add_potholes',
            name='current_activity',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='add_potholes',
            name='recent_action',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
